/*
-- Description:      Terminos y Condiciones DE APLICACION MERCADO VIRTUAL
-- @Copyright        Jorge.Muvez - World Connect Perú - 2020-00-00
*/

/* COMPONENTES */
import React from 'react';

/* VARIABLES GLOBALES */
const estadoInicial = {};

export class TerminosCondiciones extends React.Component {
    constructor(props) {
        super(props);
        this.state = estadoInicial;
    }

    redireccionar = (ruta) => { window.location.href = (this.props.urlAplicacion + ruta) }

    render() {
        return (
            <div className="TerminosCondiciones">
                <h1 className="texto_temaRojo centrado">Términos y Condiciones</h1>
                <p><strong>“POLÍTICAS DE PRIVACIDAD DE DATOS PERSONALES”</strong> El presente aviso tiene como propósito principal informar a nuestros clientes que Reactiva-Perú, en adelante la empresa, cumple las disposiciones contenidas en la Ley de Protección de Datos Personales – (Ley No. 29733) y sus normas complementarias y conexas.</p>
                <p><strong>I. FINALIDAD DE LOS DATOS SOLICITADOS</strong></p>
                <p>Reactiva-Perú podrá solicitar a sus clientes, proveedores, trabajadores, postulantes, y usuarios de esta página web (en adelante, los Titulares de los Datos Personales) datos personales con la siguiente finalidad:</p>
                <ol>
                    <li>Para la promoción de los servicios de la empresa.</li>
                    <li>Para fines comerciales relacionados con los servicios ofrecidos por Reactiva-Perú y sus empresas vinculadas.</li>
                    <li>Para la verificación y consulta de información de clientes, proveedores, trabajadores y/o postulantes.</li>
                    <li>Por motivos de seguridad.</li>
                    <li>Para compartir información con otras sucursales de Reactiva-Perú cuya necesidad esté estrictamente relacionada con la prestación de los servicios de la empresa.</li>
                </ol>
                <p>Queda expresamente establecido Reactiva-Perú reconoce el derecho de los Titulares de los Datos Personales a manifestar su negativa respecto al uso y tratamiento de sus datos personales, cuando consideren que la información proporcionada no cumple ninguna de las funciones anteriormente descritas, o si los datos brindados no son necesarios para el establecimiento de una relación contractual. Esto sin perjuicio del derecho de revocación de consentimiento previamente otorgado por parte del Titular de los Datos Personales o bien para ejercer su derecho de oposición al uso de sus datos en términos de las disposiciones aplicables, derechos que en todo caso serán garantizados por la empresa en todo momento.</p>
                <p>Los Datos Personales proporcionados serán incorporados, según corresponda a las bases de datos de (i) clientes, (ii) proveedores, (iii) postulantes, trabajadores, y extrabajadores; así como podrán incorporarse, con las mismas finalidades, a otras bases de datos de Reactiva-Perú y/o de otras empresas subsidiarias, filiales, asociadas, afiliadas o miembros del grupo económico al cual ésta pertenece y/o terceros con los que éstas mantengan una relación contractual.</p>
                <p><strong>II. OBTENCIÓN Y TRATAMIENTO DE LOS DATOS PERSONALES</strong></p>
                <p>Reactiva-Perú podrá obtener información sobre el Titular de los Datos Personales, por cualquier medio permitido por la Ley, incluyendo mas no limitándose a la obtención de manera personal o mediante plataformas electrónicas y/o páginas web. El Titular de los Datos Personales, mediante el ingreso de sus datos en la Página Web o su entrega de manera presencial, autoriza expresamente a Reactiva-Perú y/o su personal administrativo autorizado a tratar la información facilitada de conformidad con las disposiciones de la Ley de Protección de Datos Personales – Ley No. 29733, su Reglamento, normas conexas y complementarias. Reactiva-Perú procesará y protegerá los datos del Titular de los Datos Personales a través de medios digitales, técnicos y/o administrativos para garantizar un óptimo nivel de seguridad.</p>
                <p>Reactiva-Perú es responsable de guardar la información otorgada por el Titular de los Datos Personales con absoluta reserva y confidencialidad, comprometiéndose a adoptar todas las medidas de control y seguridad necesarios para evitar la alteración, uso, tratamiento, pérdida y/o acceso por terceros no autorizados. El Titular de los Datos Personales expresamente declara que toda la información que ponga a disposición de Reactiva-Perú es exacta, cierta y brindada de buena fe, liberando expresamente por este acto a Reactiva-Perú de cualquier responsabilidad en relación con la veracidad de dicha información, la misma que incluye mas no se limita a los datos personales, laborales, patrimoniales y referencias personales del Titular de los Datos Personales.</p>
                <p><strong>III. EJERCICIO DE LOS DERECHOS DE ACCESO, RECTIFICACIÓN, CANCELACIÓN U OPOSICIÓN (DERECHOS ARCO)</strong></p>
                <p>El Titular de los Datos Personales es responsable de la exactitud, veracidad y autenticidad de los datos que proporcione. Los Titulares de los Datos Personales tendrán derecho de acceder a sus datos personales que hubieren sido recabados, efectuar correcciones a los mismos en caso de ser estos inexactos o incompletos, solicitar su eliminación cuando consideren que no son necesarios para alguna de las finalidades señaladas en la Política de Privacidad cuando esta sea legalmente procedente, y; a oponerse al uso o tratamiento de sus datos, en términos de la Ley y las disposiciones aplicables.</p>
                <p>El Titular de los Datos Personales puede ejercer sus derechos de acceso, información, rectificación, cancelación, oposición y revocación al uso de sus datos personales dirigiendo su solicitud con los requisitos solicitados en la Ley y demás normas aplicables de manera presencial o a la siguiente dirección electrónica info@reactiva-peru.com.</p>
                <p><strong>IV. REVOCACIÓN DE CONSENTIMIENTO</strong></p>
                <p>El Titular de los Datos Personales podrá en cualquier momento informar a Reactiva-Perú su voluntad de revocar el consentimiento que previamente le hubiere otorgado para el tratamiento de sus datos personales, con las finalidades descritas en la Política de Privacidad establecida. Como consecuencia de la revocación del consentimiento Reactiva-Perú cesará el tratamiento de estos, salvo en aquellos casos expresamente establecidos en el artículo 14 de la Ley de Protección de Datos Personales, que regula los supuestos en los que no será necesaria la obtención del consentimiento del Titular de los Datos Personales para su tratamiento. Debe tenerse en cuenta que la revocación del consentimiento no surtirá efectos retroactivos en ningún caso.</p>
                <p><strong>V. PROCEDIMIENTO PARA EL EJERCICIO DE LOS DERECHOS CONTENIDOS EN LA LEY DE PROTECCIÓN DE DATOS PERSONALES.</strong></p>
                <p>El Titular de los Datos Personales puede ejercer directamente sus derechos de acceso, información, rectificación, cancelación, oposición y revocación al uso de tus datos personales-directamente a través de un representante legal- dirigiendo su solicitud con los requisitos solicitados en la Ley y demás norma aplicables, dirigiendo su solicitud a la siguiente dirección de correo electrónico: info@reactiva-peru.com.</p> <p>A la solicitud se deberá anexar, como archivo adjunto, una copia del DNI del Titular de los Datos Personales y de ser el caso, adicionalmente el de su representante. Asimismo, deberá consignarse la siguiente información:</p>
                <ul>
                    <li>Nombres y apellidos del titular del derecho y una copia de su documento de identidad (DNI o Carne de Extranjería).</li>
                    <li>De ser el caso, datos de identificación del representante del Titular de los Datos Personales, copia de su documento de identidad (DNI o Carne de Extranjería), y una carta poder (con firmas legalizadas) otorgada por el Titular de los Datos Personales.</li>
                    <li>Petición concreta que da lugar a la solicitud.</li>
                    <li>Domicilio y/o correo electrónico, a efectos de las notificaciones que correspondan.</li>
                    <li>Fecha y firma del solicitante.</li>
                    <li>Documentos que sustenten la petición, de ser el caso.</li>
                </ul>
                <p>Asimismo, el Titular de los Datos Personales -o su representante- deberá indicar a través de qué medio Reactiva-Perú deberá facilitarle la información solicitada, pudiendo ser (i) a través de su visualización en las instalaciones de los restaurantes, karaokes, discotecas y hoteles que forman parte de la empresa; (ii) por escrito, copia o fotocopia; (iii) mediante trasmisión electrónica, para lo cual se deberá indicar la dirección de correo electrónico a la que se deberá remitir la información; u (iv) otra forma idónea y razonable. La revocación de la autorización no requiere de motivación alguna por parte del Titular de los Datos Personales.</p> <p>Recibida una solicitud, Reactiva-Perú tendrá un plazo de cinco (5) días hábiles para formular observaciones por incumplimiento que no puedan ser salvadas de oficio, otorgando al solicitante un plazo máximo de cinco (5) días hábiles para subsanarlas, de lo contrario, la solicitud se tendrá por no presentada. A partir de la fecha en la que se recibe la solicitud, se computará un plazo de diez (10) días hábiles para dar respuesta al Titular de los Datos Personales. Tratándose del ejercicio del derecho de acceso, el plazo será de veinte (20) días hábiles desde el día siguiente de la presentación de la solicitud.</p>
                <p><strong>VI. LIMITACIÓN DEL USO O TRANSFERENCIA DE DATOS PERSONALES.</strong></p>
                <p>Si los datos personales ingresados por el Titular de los Datos Personales no resultan necesarios para el cumplimiento de las obligaciones resultantes de la relación jurídica existente entre él mismo y el Titular de los Datos Personales, el primero podrá solicitar a Reactiva-Perú que limite la divulgación, uso y/o transferencia de dichos datos mediante solicitud expresa siguiendo el procedimiento señalado en el acápite V de estas Políticas. De resultar procedente dicho pedido, Reactiva-Perú detallará los datos personales prescindibles para la relación jurídica que mantiene con el Titular de los Datos Personales, los cuales serán excluidos del banco de datos personales dentro de los 10 (diez) días hábiles siguientes a la presentación de la solicitud de baja.</p>
                <p><strong>VII. TRANSFERENCIA DE DATOS PERSONALES POR SERVICIOS DE REACTIVA-PERÚ</strong></p>
                <p>Los Datos Personales facilitados por sus Titulares podrán ser compartidos entre las empresas del grupo Reactiva-Perú. En el caso de transferencia de los datos a terceros, la empresa garantizará que los receptores actuarán conforme a lo dispuesto en la Ley Nº 29733 – Ley de Protección de Datos Personales y su Reglamento; siendo que tales datos personales serán utilizados únicamente para las finalidades de tratamiento enunciadas. Los representantes y colaboradores podrán dedicarse, de forma no limitativa, a la realización de actividades de un giro similar a Reactiva-Perú o estar ligadas a Reactiva-Perú por una relación contractual. Lo anteriormente expuesto incluye, pero no se limita a despachos de cobranza, entidades financieras (nacionales o extranjeras), Instituciones de Seguros y/o Fianzas, y personas naturales y jurídicas que le presten servicios a Reactiva-Perú.</p>
                <p><strong>VIII. CONSENTIMIENTO POR TRANSFERENCIA</strong></p>
                <p>El Titular de los Datos Personales concede su expresa conformidad y faculta a Reactiva-Perú a realizar las transferencias en los supuestos previstos en el presente Aviso de Privacidad, a los terceros mencionados en el punto cinco y de acuerdo con las finalidades ahí establecidas.</p>
                <p><strong>IX. COOKIES Y REDES SOCIALES</strong></p>
                <p>El Titular de los Datos Personales que tenga acceso a la “Página Web”, acuerda recibir las Cookies que les transmitan los servidores de Reactiva-Perú. Una cookie es todo tipo de “Archivo” o “Dispositivo” que se descarga en un “Equipo Terminal” (Ordenador, Teléfono Móvil, Tableta u otro) de cualquier “Titular de los Datos Personales” (tanto Persona Física como Persona Jurídica), con la finalidad de Almacenar Datos (desde pocos Kilobytes a muchos Megabytes) y que podrán ser actualizados y/o recuperados por la Entidad responsable de la instalación. Una Cookie no puede leer los datos o información del disco duro del Titular de los Datos Personales ni leer las Cookies creadas por otros sitios o páginas. Los presentes Términos y condiciones de Uso y Privacidad corresponden únicamente a los servicios de Reactiva-Perú. La empresa no tiene control alguno sobre los sitios web mostrados como resultados de búsquedas o enlaces que se incluyen en nuestra “Página Web”. Es posible que estos sitios independientes envíen sus propias cookies u otros archivos a su equipo, recopilen datos o le soliciten que envíe información personal.</p> <p>Las redes sociales constituyen una plataforma de comunicación y de interconexión entre plataformas digitales de los distintos usuarios, las cuales son ajenas a Reactiva-Perú y, por ello, no se encuentran bajo su responsabilidad. La información y datos proporcionados por el Titular de los Datos Personales dentro de las redes sociales de las cuales Reactiva-Perú sea usuario, no constituyen en ningún momento parte de la información personal o sensible sujeta a la protección de este Política de Privacidad, siendo responsabilidad de la empresa prestadora de esa plataforma y de quien lo publica.</p>
                <p><strong>X. COMUNICACIONES</strong></p>
                <p>Cualquier modificación total o parcial a las disposiciones enumeradas en la presente Política de Privacidad se dará a conocer a través de cualquiera de los siguientes medios: un comunicado por escrito enviado al domicilio del Titular de los Datos Personales o publicado dentro de las instalaciones de la empresa; un mensaje enviado a su correo electrónico o a su teléfono móvil; un mensaje dado a conocer a través cualquier medio electrónico que utilice para celebrar operaciones con la empresa o bien a través de los sitios web de Reactiva-Perú</p>
            </div>
        )
    }
}

export default TerminosCondiciones;